export const domainList = [
  { label: '安全域', value: '1' },
  { label: '支付结算域', value: '2' },
  { label: '账务域', value: '3' },
  { label: '交易域', value: '4' },
  { label: '产品域', value: '5' },
  { label: '标的域', value: '6' },
  { label: '履约域', value: '7' },
  { label: '承保域', value: '8' },
  { label: '批改域', value: '9' },
  { label: '营销域', value: '10' },
  { label: '合约域', value: '11' },
  { label: '单证域', value: '12' },
  { label: '客户接触域', value: '13' },
  { label: '客户域', value: '14' },
  { label: '合作开放域', value: '15' },
  { label: '运营支撑域', value: '16' },
  { label: '合约域', value: '17' },
  { label: '保单服务域', value: '18' },
];

export const domainMap: Record<string, string> = {
  risk: '1',
  payment: '2',
  accounts: '3',
  4: '4',
  product: '5',
  insuredobject: '6',
  'agrmt-execution': '7',
  undertake: '8',
  endorse: '9',
  promotion: '10',
  contract: '11',
  document: '12',
  'customer-contact': '13',
  customer: '14',
  cooperation: '15',
  aboss: '16',
  policy: '18',
};
